Repository dalihub/TizenFX, pull requests merged in 2019-10, with the labels that each got.

#33 [NUI] Enable View.ScaleBy
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: ACR Required, API6, Internal API Changed

#35 [NUI] sync from samsung into dalihub
  packaging/PlatformFileList.txt
  src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs
  src/Tizen.NUI.Components/Attributes/LoadingAttributes.cs
  src/Tizen.NUI.Components/Attributes/PaginationAttributes.cs
  src/Tizen.NUI.Components/Attributes/TabAttributes.cs
  src/Tizen.NUI.Components/Attributes/ViewAttributes.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI/src/public/Key.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc.sln
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommand.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceControlManagerClient.cs
Labels: ACR Required, API6, Internal API Changed

#22 [NUI] Fix gesture callback issue
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
Labels: ACR Required, API6, Internal API Changed

#36 [NUI]fix flexible crash when scrolling
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
Labels: ACR Required, API6, Internal API Changed

#37 fix layout issue of flexibleview when animation is canceled
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
Labels: API6

#21 [NUI] Split large files
  src/Tizen.NUI/src/internal/AccessibilityManager.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEventArgs.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/VisualConstants.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
  src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/BorderVisual.cs
  src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
  src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
  src/Tizen.NUI/src/public/Visuals/ImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/MeshVisual.cs
  src/Tizen.NUI/src/public/Visuals/NPatchVisual.cs
  src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
  src/Tizen.NUI/src/public/Visuals/SVGVisual.cs
  src/Tizen.NUI/src/public/Visuals/TextVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
  src/Tizen.NUI/src/public/Window.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: ACR Required, API6, Internal API Changed

#40 Added Rotation Gesture Support
  src/Tizen.NUI/src/internal/Interop/Interop.RotationGesture.cs
  src/Tizen.NUI/src/internal/RotationGestureDetectedSignal.cs
  src/Tizen.NUI/src/public/RotationGesture.cs
  src/Tizen.NUI/src/public/RotationGestureDetector.cs
Labels: ACR Required, API6, Internal API Changed

#41 [NUI] Sync from Samsung into dalihub
  internals/src/EflSharp/EflSharp/Circle/CircleGenlist.cs
  internals/src/EflSharp/EflSharp/Circle/CircleScroller.cs
  internals/src/EflSharp/EflSharp/Circle/RotarySelector.cs
  internals/src/EflSharp/EflSharp/efl/efl_access_object.eo.cs
  internals/src/EflSharp/EflSharp/efl/efl_ui_animation_view.eo.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowEffectEventSignal.cs
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/WidgetViewSignal.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/PropertyBuffer.cs
  src/Tizen.NUI/src/public/PropertyNotifySignal.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: ACR Required, API6, Internal API Changed

#42 [NUI] Integration from samsung github
  src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/Disposable.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/Accessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed
